# Generated by Django 2.0 on 2019-03-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='authorDetail',
        ),
        migrations.DeleteModel(
            name='AuthorDetail',
        ),
    ]
